### ISSUE TITLE
Add PDB social media to web page footer

### ISSUE THREAD

**Issue by ghankins** [peeringdb/docs#102]
There's a nice blank space on the left side under the version number for social media badges.

Add:
Twitter: https://twitter.com/PeeringDB
Facebook: https://www.facebook.com/peeringdb/

Facebook badge: https://www.facebookbrand.com/ -> https://www.facebookbrand.com/img/assets/asset.f.logo.lg.png
Twitter badge: https://about.twitter.com/company/brand-policy -> http://www.open-ix.org/wp-content/uploads/2016/04/twitter.png (I cropped this badge from the official ones)

It should look something like this but without LinkedIn.
![untitled2](https://cloud.githubusercontent.com/assets/8171907/14582334/c698e03c-03cf-11e6-99d7-878b23768b3b.png)

**Comment by ghankins** [comment]
Could also use the badges the docs page...

Facebook Like/Share
Follow us on Twitter

http://docs.peeringdb.com/#mailing-lists

**Comment by ghankins** [comment]
Don't know why this opened a new issue.

**Comment by ghankins** [comment]
This issue is for the main page.

**Comment by grizz** [comment]
Fixed in https://github.com/peeringdb/docs/pull/108
