### ISSUE TITLE
improve approval notifications

### ISSUE THREAD

**Issue by job** [peeringdb/docs#103]
All the `admin` level users within an organisation get the `User XX YY wishes to be affiliated to your Organization` emails, but it would be useful if there is a follow-up email to the same group of email addresses that says `Admin ZZ approved User XX YY to be affiliated with organisation AA`. This way people know that the request has been handled and who handled it.

**Comment by grizz** [comment]
want auto reply for Denied as well then?

**Comment by job** [comment]
Yes

**Comment by grizz** [comment]
Moved to peeringdb/peeringdb/issues/19
