### ISSUE TITLE
Whois: an error occurred

### ISSUE THREAD

**Issue by ghankins** [peeringdb/docs#104]
Reported by Peter Hessler on BSD client, but the same error happens on Linux too:

whois -h whois.peeringdb.com as20940

blah blah

Interxion Madrid (MAD1, MAD2)                       20940    Madrid          ES
Interxion Frankfurt 2                               20940    Frankfurt       DE
KDDI Otemachi (Telehouse Tokyo Otemachi)            20940    Tokyo           JP
Interxion Copenhagen                                20940    Copenhagen      DK
an error occurred

**Comment by grizz** [comment]
Moved to peeringdb/peeringdb/issues/17
