### ISSUE TITLE
Facility query should return number of networks present in facility 

### ISSUE THREAD

**Issue by stevemeuse** [peeringdb/docs#106]
I feel like this was in the original version, when I queried for facilities in a given locality, the resulting list would include the numbers of networks in each facility. 

I.E. When I'm looking at facilities in NYC, I was to know which have the most. Currently I have to click into each one to see the totals.

**Comment by job** [comment]
Network count is also missing here http://instituut.net/~job/screenshots/fd76bfabd979d4e4228b4f24.png

Can this be flagged as a bug? Its very annoying :)

**Comment by vegu** [comment]
fixed 8120971 (fix will be pushed with version 2.0.11)
