### ISSUE TITLE
Get by ASN only searches primary ASN

### ISSUE THREAD

**Issue by agallo** [peeringdb/docs#35]
A network that has multiple ASNs isn't returned when requesting non-primary ASN.

For example, APNIC (id=3103) has the primary ASN 4608, but different ASNs at different IXs (for example ASN 18369 at Equinix-Ashburn (fac=1))

`https://beta.peeringdb.com/api/asn/4608` returns APNIC's record, but `https://beta.peeringdb.com/api/asn/18369` does not.

Searching on the web interface yields the same results (specifically, searchers for 18369 returns no results).

Shouldn't a get or search work for all ASNs for a given org?

**Comment by agallo** [comment]
Should have checked the original website.  Search is for primary ASN only, so this isn't a bug.

I'll leave this open with this question - any plans to implement searching for all ASNs associated with a given network?

**Comment by grizz** [comment]
Yep, it's a good idea.

**Comment by grizz** [comment]
Moved to peeringdb/peeringdb/issues/28
