### ISSUE TITLE
autofil recommend_max_prefix_v6

### ISSUE THREAD

**Issue by job** [peeringdb/docs#38]
In the old PeeringDB we only have 1 field for "recommended max prefix setting" which is called "Approx Prefixes". Almost all networks have filled in the recommended max prefix setting for IPv4.

Going forward in 2.0 we'll have two fields, one max prefix recommendation for IPv4 and one for IPv6. I recommend that the initial autofill of the ```recommended_max_prefix_v6``` field is done by taking the "Approx Prefixes" value from PDB1, and multiplying it with ```0.05```. ```recommended_max_prefix_v4``` should just be copied from "Approx Prefixes" in PDB1.

**Comment by grizz** [comment]
It's already done like that

**Comment by job** [comment]
Needs to be fixed in ```management/commands/old_import.py```, but need to keep in mind that a proper integer needs to come out. Assigned to myself pending a proper test setup :-)

**Comment by htj** [comment]
Just a friendly reminder to fix this before going live with 2.0. The current translation is quite dangerous IMHO, as many networks have more v4 prefixes visible than a full v6 table (20K currently).

Having an prefix-limit larger than 20K is just a waste of configuration lines. In fact, more than 10K seems rather unlikely as well. We have HE at around 13K, and NTT around 10K. Rest is very low.

**Comment by grizz** [comment]
This is quite trivial to do any time, we'll take care of it one of the upcoming releases.

**Comment by job** [comment]
We're still debating how to sanitise the data. It appears that some networks use the "prefixes" value to express how many prefixes are in their customer cone, while others use it to express "preferred max prefix you set on your side of the sessions" and to make it worse some have not updated their values in years.

I'm uncertain about immediate danger or urgency, because in PDB1 there was no difference between the two. Whatever people used when integrating with pdb1 - whatever logic they apply, will still apply today. Also I prefer not to touch people's data, they should maintain it themselves.

One way forward is to provide people with a popup or email alert that we suspect their IPv6 prefix count needs updating and hope that people proactively work on it. But we should also think about maybe separating between "announced prefix count" and "suggested max pfx count" - or if we dont want to do 4 fields, more clearly defining what it is we mean with the datafield.

**Comment by grizz** [comment]
Moved to peeringdb/peeringdb/issues/27
