### ISSUE TITLE
Support for multiple IRR records, identify source

### ISSUE THREAD

**Issue by listerr** [peeringdb/docs#56]
The current database only has one field for a single IRR record, and many networks have multiple, for example separate for IPv4 and IPv6, or different IRR record for customers/peers/regions etc.

The source of the IRR record is not identified - is it in RIPE, RADB, ALTDB etc?

Is there any intention to allow multiple? What seems to happen now is that the field can contain multiple IRR records in a variety of interesting ways, and parsing this is of course a pain.

Is the schema available anywhere?

**Comment by grizz** [comment]
Good idea, we'll add that in.

Abstract base schema is at:
https://github.com/peeringdb/django-peeringdb/blob/master/django_peeringdb/models/abstract.py

**Comment by grizz** [comment]
Moved to peeringdb/peeringdb/issues/26
