### ISSUE TITLE
Add operation to API to look for covering prefixes given an IP

### ISSUE THREAD

**Issue by seb-at-nzrs** [peeringdb/docs#61]
While testing the REST API to lookup if a given IP address belongs to an IX in the PeeringDB database, I came up with the less than ideal solution:

For address 206.223.118.117 search as

https://beta.peeringdb.com/api/ixpfx?prefix__startswith=206.223.118

Will return a prefix and a ixlan_id that can be used to query up to the organization.

But if the prefix is not aligned with the octet (v4) or nibble (v6), the solution doesn't work. 
Have you considered an special lookup for find matching network? The
simplest option is "find a prefix that covers this address", although
the generic option is "find a prefix that covers this prefix", and then addresses can be search as 'x.x.x.x/32' or 'dead::beef/128'

If the backend code is available somewhere, I'll be happy to provide a patch.

**Comment by grizz** [comment]
Moved to peeringdb/peeringdb/issues/25
