### ISSUE TITLE
High variance in response time

### ISSUE THREAD

**Issue by htj** [peeringdb/docs#71]
I've been changing our system to use the v2 api over a couple of days.

The response times for using the api seems to vary greatly. Sometime responses are instant, but often they will take 4-5 seconds, sometimes 10-20 seconds.

**Comment by grizz** [comment]
Should be all fixed after the production rollout

**Comment by htj** [comment]
Nope.

htj@pyrite:~/ncs/ndn-ncs/packages/bgp-peer/src/java$ time curl --silent "https://www.peeringdb.com/api/net?asn=6774&depth=2" > /dev/null

real	0m0.875s
user	0m0.052s
sys	0m0.020s
htj@pyrite:~/ncs/ndn-ncs/packages/bgp-peer/src/java$ time curl --silent "https://www.peeringdb.com/api/net?asn=6774&depth=2" > /dev/null

real	0m6.301s
user	0m0.048s
sys	0m0.028s
htj@pyrite:~/ncs/ndn-ncs/packages/bgp-peer/src/java$ time curl --silent "https://www.peeringdb.com/api/net?asn=6774&depth=2" > /dev/null

real	0m0.790s
user	0m0.056s
sys	0m0.016s
htj@pyrite:~/ncs/ndn-ncs/packages/bgp-peer/src/java$ time curl --silent "https://www.peeringdb.com/api/net?asn=6774&depth=2" > /dev/null

real	0m0.788s
user	0m0.048s
sys	0m0.028s
htj@pyrite:~/ncs/ndn-ncs/packages/bgp-peer/src/java$ time curl --silent "https://www.peeringdb.com/api/net?asn=6774&depth=2" > /dev/null

real	0m0.808s
user	0m0.060s
sys	0m0.012s

**Comment by htj** [comment]
You might want to give users the option of re-opening tickets.

**Comment by grizz** [comment]
I'm still unable to reproduce, this is from my home workstation some 12hops/35ms away with various attempts at cache misses.

+ curl --silent https://www.peeringdb.com/api/net?asn=6774&depth=2
times: 0.259 0.26 0.253 0.252 0.257 0.261 0.261 0.254 0.343 0.253 0.252
count: 11 min: 0.252 max: 0.343 med: 0.257 avg: 0.264091

+ time curl --silent https://www.peeringdb.com/api/net?asn=6774&depth=2
times: 0.256 0.266 0.254 0.248 0.257 0.254 0.297 0.253 0.253 0.258 0.258
count: 11 min: 0.248 max: 0.297 med: 0.256 avg: 0.259455

+ time curl --silent https://www.peeringdb.com/api/net?asn=6774&depth=4
times: 0.252 0.294 0.278 0.255 0.261 0.252 0.257 0.254 0.252 0.25 0.248
count: 11 min: 0.248 max: 0.294 med: 0.254 avg: 0.259364

+ time curl --silent https://www.peeringdb.com/api/net?asn=63311&depth=4
times: 1.698 0.191 0.189 0.194 0.189 0.194 0.192 0.199 0.191 0.194 0.191
count: 11 min: 0.189 max: 1.698 med: 0.192 avg: 0.329273

+ time curl --silent https://www.peeringdb.com/api/net?asn=4436&depth=4
times: 0.352 0.347 0.349 0.349 0.431 0.385 0.348 0.355 0.343 0.351 0.348
count: 11 min: 0.343 max: 0.431 med: 0.349 avg: 0.359818

From what I can tell, users are able to re-open issues, do you know of a setting somewhere else?

**Comment by job** [comment]
@htj can you run `tcpdump -w pdb.pcap -s 0 host peeringdb.com` and in a second terminal run `date; time time curl --silent "https://www.peeringdb.com/api/net?asn=6774&depth=2" > /dev/null` a few times and email me the PCAP or link it here?

**Comment by grizz** [comment]
Assuming this is all fine now, let is know if you're still seeing issues.
