### ISSUE TITLE
Language Abstraction support (Portugese as second language)

### ISSUE THREAD

**Issue by job** [peeringdb/docs#90]
AdminCom has seen a significant uptake in support related work items from organisations residing in Portugese speaking countries. The language barrier sometimes makes things a bit difficult. I'd like to serve PeeringDB in Portugese in conjunction with the current English texts.

AdminCom can arrange for translations if a language abstraction engine of sorts is available.

**Comment by grizz** [comment]
Moved to peeringdb/peeringdb/issues/22
