### ISSUE TITLE
Include VLAN names in /ix "Peers at this Exchange Point" listing

### ISSUE THREAD

**Issue by vegu** [peeringdb/docs#98]
on an IX listing such as https://www.peeringdb.com/ix/13, the VLAN name should be displayed within the "Peers at this Exchange Point" listing, otherwise it seems like everyone is in the same VLAN.

**Comment by grizz** [comment]
Yet another reason to drop IX Lans (see http://lists.peeringdb.com/pipermail/pdb-tech/2016-April/000104.html)

**Comment by vegu** [comment]
fixed ace40a8 - Added ixlan name for now, will leave ticket open for further discussion

**Comment by grizz** [comment]
Moved to peeringdb/peeringdb/issues/21 for discussion
